[package]
name = "ping"
version = "0.1.0"
edition = "2021"
author = "Christopher Wróbel"
about = "A Demo Networking Utility in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.34.0"
clap = { version = "4.4.8", features = ["derive"] }
